apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ogxserver.yaml
- pizza-topping-skill.yaml

secretGenerator:
- name: ogx-demo-secrets
  envs:
  - .env.secret
  options:
    disableNameSuffixHash: true

configMapGenerator:
- name: ogx-demo-config-fs
  files:
  - config.yaml
  options:
    labels:
      ogx.io/watch: "true"
    disableNameSuffixHash: true
