apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wn-responses-${SUFFIX}
spec:
  to:
    kind: Service
    name: wn-responses-service
  port:
    targetPort: 8321
  tls:
    termination: edge
